### ISSUE TITLE
suds.TypeNotFound: Type not found: 'Key'

### ISSUE THREAD

**Issue by andreabisello** [cackharot/suds-py3#44]
with this wsdl endpoint

https://testsdc2csolution.solutiondocondemand.com/Basic/RepositoryService.svc?wsdl

i'm not able to send data to the createDocument method,

that works using soapui.

![image](https://user-images.githubusercontent.com/2149815/67615671-9618a800-f7cf-11e9-8e44-8e832a272580.png)

this is the code. i try to add a doctor adding all the namespace, but nothing changed, the problem still 

`suds.TypeNotFound: Type not found: 'Key'`

this is the python3 code with everything updated

```



imp = Import('http://tempuri.org/Imports')
imp.filter.add('https://tempuri.org/')
imp.filter.add('https://schemas.microsoft.com/2003/10/Serialization/')
imp.filter.add('https://docs.oasis-open.org/ns/cmis/messaging/200908/')
imp.filter.add('https://docs.oasis-open.org/ns/cmis/core/200908/')
imp.filter.add('https://schemas.microsoft.com/2003/10/Serialization/Arrays')
imp.filter.add('https://schemas.datacontract.org/2004/07/WcfConservazione')
imp.filter.add('https://schemas.datacontract.org/2004/07/SdC_ConservazioneSDK')
imp.filter.add('https://schemas.datacontract.org/2004/07/SdC_ConservazioneSDK.SdC')
imp.filter.add('https://schemas.datacontract.org/2004/07/SdC_ConservazioneSDK.SdCInput')
doctor = ImportDoctor(imp)


client = Client("https://testsdc2csolution.solutiondocondemand.com/Basic/RepositoryService.svc?wsdl", username=CONSERVAZIONE_USERNAME, password=CONSERVAZIONE_PASSWORD, doctor=doctor)
client.set_options(wsse=security)
print(client)

c_stream = file_to_b64bytes("assets/pdv/packagePdV.zip")
c_length = len(c_stream)

proprieta1 = client.factory.create('ns7:KeyValueOfstringanyType')
print(proprieta1)
proprieta1.Key = "PdV_VerificaFirmaFiles"
proprieta1.Value = False

proprieta2 = client.factory.create('ns7:KeyValueOfstringanyType')
proprieta2.Key = "Firma_OggettiProduttore"
proprieta2.Value = False

content_stream = client.factory.create('ns0:ContentStream')
content_stream.filename = "packagePdV.zip"
content_stream.length = c_length
content_stream.stream = c_stream

risposta = client.service.createDocument(
    repositoryId=1,
    properties=[proprieta1,proprieta2],
    contentStream=content_stream
)




```

the data structure looks good

this is the log

```

C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\python.exe C:/src/qa-lsd-webservices/qa-lsd-webservices/prova.py
C:\src\qa-lsd-webservices\qa-lsd-webservices\lib

Suds ( https://github.com/cackharot/suds-py3 )  version: 1.3.3.0 IN  build: 20170311

Service ( RepositoryService ) tns="http://tempuri.org/"
   Prefixes (9)
      ns0 = "http://docs.oasis-open.org/ns/cmis/core/200908/"
      ns1 = "http://docs.oasis-open.org/ns/cmis/messaging/200908/"
      ns2 = "http://schemas.datacontract.org/2004/07/SdC_ConservazioneSDK"
      ns3 = "http://schemas.datacontract.org/2004/07/SdC_ConservazioneSDK.SdC"
      ns4 = "http://schemas.datacontract.org/2004/07/SdC_ConservazioneSDK.SdCInput"
      ns5 = "http://schemas.datacontract.org/2004/07/WcfConservazione"
      ns6 = "http://schemas.microsoft.com/2003/10/Serialization/"
      ns7 = "http://schemas.microsoft.com/2003/10/Serialization/Arrays"
      ns8 = "http://tempuri.org/"
   Ports (1):
      (RepositoryServicePortBasic)
         Methods (79):
            addPdVToAntiVirusQueue(xs:string idPdV, xs:string idSetup, xs:int idAzienda, )
            cancelPdV(xs:string idPdV, xs:string motivoAnnullamento, )
            checkArchiviazionePdV(xs:string idPdV, )
            checkIndicePdV(ns7:ArrayOfKeyValueOfstringanyType properties, ns0:ContentStream contentStream, )
            checkRemoteSign(xs:string urlService, xs:string userNameFirma, xs:string passwordFirma, )
            createAzienda(ns3:AziendaSdC az, )
            createDocument(xs:string repositoryId, ns7:ArrayOfKeyValueOfstringanyType properties, ns0:ContentStream contentStream, ns0:VersioningState versioningState, ns7:ArrayOfstring policies, )
            createDocumentLocal(ns7:ArrayOfKeyValueOfstringanyType properties, xs:string pathFileZip, xs:string pathFolderEsito, )
            createLavoro(ns3:LavoroSdC l, )
            createPdA(xs:string idLavoro, ns3:OpzioniSdC options, )
            createPdD(xs:string idSetup, xs:int idAzienda, ns3:UtenteSdC userRichiedente, ns7:ArrayOfstring elencoIdPdV, ns3:ArrayOfDocTipologiaSdC elencoIdDoc, )
            createPdDInfo(xs:string idSetup, xs:int idAzienda, ns3:UtenteSdC userRichiedente, ns4:RequestPdDParam requestPdD, )
            createRdV(xs:string idSetup, xs:int idAzienda, )
            createSoggetto(ns3:SoggettoSdC s, )
            createUser(ns3:UtenteSdC user, )
            deletePendingRequest(xs:string idRequest, )
            deleteUser(xs:string idUser, )
            exportDoc(xs:string idSetup, xs:int idAzienda, ns3:DocTipologiaSdC idDoc, )
            exportIndexPdV(xs:string idPdV, )
            exportRdAV(xs:string idRdAV, )
            exportRdV(xs:string idRdV, )
            exportSearchDoc(xs:string idSetup, xs:int idAzienda, xs:string jsonQuery, ns4:ExportSearchDocParam exportParam, ns2:PagingCriteria criteria, )
            getAllAntiVirusQueue(xs:string idSetup, xs:int idAzienda, xs:string stato, ns2:PagingCriteria criteria, )
            getAllAntiVirusQueueCount(xs:string idSetup, xs:int idAzienda, xs:string stato, )
            getAllAziende(xs:string idSetup, ns2:PagingCriteria criteria, )
            getAllAziendeCount(xs:string idSetup, )
            getAllDocument(xs:string idSetup, xs:int idAzienda, xs:string jsonQuery, ns2:PagingCriteria criteria, )
            getAllDocumentCount(xs:string idSetup, xs:int idAzienda, xs:string jsonQuery, )
            getAllLavori(xs:string idSetup, xs:int idAzienda, xs:string descrizione, ns2:PagingCriteria criteria, )
            getAllLavoriCount(xs:string idSetup, xs:int idAzienda, xs:string descrizione, )
            getAllLog(xs:string idSetup, xs:int idAzienda, xs:dateTime dataInizio, xs:dateTime dataFine, xs:string levelLog, ns2:PagingCriteria criteria, )
            getAllLogCount(xs:string idSetup, xs:int idAzienda, xs:dateTime dataInizio, xs:dateTime dataFine, xs:string levelLog, )
            getAllLogPdV(xs:string idPdV, ns2:PagingCriteria criteria, )
            getAllLogPdVCount(xs:string idPdV, )
            getAllPdA(xs:string idSetup, xs:int idAzienda, ns4:FilterPdAParam filter, ns2:PagingCriteria criteria, )
            getAllPdACount(xs:string idSetup, xs:int idAzienda, ns4:FilterPdAParam filter, )
            getAllPdD(xs:string idSetup, xs:int idAzienda, ns4:FilterPdDParam filter, ns2:PagingCriteria criteria, )
            getAllPdDCount(xs:string idSetup, xs:int idAzienda, ns4:FilterPdDParam filter, )
            getAllPdV(xs:string idSetup, xs:int idAzienda, xs:long idTipologia, xs:dateTime dataInizio, xs:dateTime dataFine, xs:boolean annullato, xs:boolean rdvGenerato, xs:boolean conservato, ns2:PagingCriteria criteria, )
            getAllPdVCount(xs:string idSetup, xs:int idAzienda, xs:long idTipologia, xs:dateTime dataInizio, xs:dateTime dataFine, xs:boolean annullato, xs:boolean rdvGenerato, xs:boolean conservato, )
            getAllPendingRequest(xs:string idSetup, xs:int idAzienda, ns4:FilterPendingRequestParam requestParam, xs:boolean filterByUser, ns2:PagingCriteria criteria, )
            getAllRdAV(xs:string idSetup, xs:int idAzienda, ns7:ArrayOfstring elencoIdPdV, xs:dateTime dataInizio, xs:dateTime dataFine, xs:string idSoggettoRdC, ns2:PagingCriteria criteria, )
            getAllRdAVCount(xs:string idSetup, xs:int idAzienda, ns7:ArrayOfstring elencoIdPdV, xs:dateTime dataInizio, xs:dateTime dataFine, xs:string idSoggettoFirma, )
            getAllRdV(xs:string idSetup, xs:int idAzienda, ns7:ArrayOfstring elencoIdPdV, xs:dateTime dataInizio, xs:dateTime dataFine, xs:string idSoggettoRdC, ns2:PagingCriteria criteria, )
            getAllRdVCount(xs:string idSetup, xs:int idAzienda, ns7:ArrayOfstring elencoIdPdV, xs:dateTime dataInizio, xs:dateTime dataFine, xs:string idSoggettoRdC, )
            getAllSoggetti(xs:string ruolo, xs:string ragSociale, xs:string nomeCognome, ns2:PagingCriteria criteria, )
            getAllSoggettiCount(xs:string ruolo, xs:string ragSociale, xs:string nomeCognome, )
            getAllUser(xs:string idSetup, xs:int idAzienda, ns2:PagingCriteria criteria, )
            getAllUserCount(xs:string idSetup, xs:int idAzienda, )
            getAntiVirusElementFromPdV(xs:string idPdV, )
            getAzienda(xs:string idAzienda, )
            getCurrentUser()
            getDocumentAntivirusChecks(xs:string idSetup, xs:int idAzienda, ns3:DocTipologiaSdC idDoc, )
            getLavoro(xs:string idLavoro, )
            getPdV(xs:string idPdV, )
            getPdVAttachments(xs:string idPdV, )
            getPendingOperationTypes()
            getPendingRequest(xs:string idRequest, )
            getRemainingTimestamps(xs:string idSoggetto, xs:string idSetup, xs:int idAzienda, )
            getReportPdA(xs:string idSetup, xs:int idAzienda, ns4:ReportPdARequestParam reportParam, )
            getReportPdV(xs:string idSetup, xs:int idAzienda, ns4:ReportPdVRequestParam reportParam, )
            getRepositories()
            getRepositoryInfo(xs:string repositoryId, )
            getReservedExtensions()
            getSoggettiAzienda(xs:string idSetup, xs:int idAzienda, )
            getSoggetto(xs:string idSoggetto, )
            getUser(xs:string idUser, )
            recoverPdV(xs:string idPdV, xs:string motivoRipristino, )
            removePdVFromAntiVirusQueue(xs:string idPdV, )
            requestCreateDocumentFile(ns7:ArrayOfKeyValueOfstringanyType properties, xs:string fileId, )
            requestCreatePdD(xs:string idSetup, xs:int idAzienda, ns3:UtenteSdC userRichiedente, ns4:RequestMassivePdDParam requestPdD, )
            resetPendingRequest(xs:string idRequest, xs:boolean forceReset, )
            setSoggettiAzienda(xs:string idAzienda, ns7:ArrayOfstring elencoIdSoggetti, xs:string idSoggettoFirma, )
            unlockPdASchedule(xs:string idLavoro, )
            unlockRdVSchedule(xs:string idSetup, xs:int idAzienda, )
            updateAzienda(ns3:AziendaSdC az, )
            updateLavoro(ns3:LavoroSdC l, )
            updateSoggetto(ns3:SoggettoSdC s, )
            updateUser(ns3:UtenteSdC user, )
         Types (88):
            ns0:AclPropagation
            ns0:AllowableActionsKey
            ns3:AntivirusCheckSdC
            ns3:ArrayOfAziendaSdC
            ns0:ArrayOfBaseObjectTypeId
            ns3:ArrayOfDocAntivirusCheckSdC
            ns3:ArrayOfDocSdC
            ns3:ArrayOfDocTipologiaPdVSdC
            ns3:ArrayOfDocTipologiaSdC
            ns7:ArrayOfKeyValueOfstringanyType
            ns3:ArrayOfLavoroSdC
            ns3:ArrayOfLogSdC
            ns3:ArrayOfPdASdC
            ns3:ArrayOfPdDSdC
            ns3:ArrayOfPdVAntivirusSdC
            ns3:ArrayOfPdVPdDPreSdC
            ns3:ArrayOfPdVSdC
            ns0:ArrayOfPermissionDefinition
            ns0:ArrayOfPermissionMapping
            ns3:ArrayOfQueueOpSdC
            ns3:ArrayOfQueueOpTypeSdC
            ns3:ArrayOfRdAVSdC
            ns3:ArrayOfRdVSdC
            ns3:ArrayOfReportPdASdC
            ns3:ArrayOfReportPdVSdC
            ns1:ArrayOfRepositoryEntry
            ns3:ArrayOfSoggettoLavoroSdC
            ns3:ArrayOfSoggettoSdC
            ns2:ArrayOfSortingCriteria
            ns3:ArrayOfUtentePermessoSdC
            ns3:ArrayOfUtenteSdC
            ns7:ArrayOflong
            ns7:ArrayOfstring
            ns3:AziendaSdC
            ns0:BaseObjectTypeId
            ns0:CapabilityAcl
            ns0:CapabilityChanges
            ns0:CapabilityContentStreamUpdates
            ns0:CapabilityJoin
            ns0:CapabilityQuery
            ns0:CapabilityRendition
            ns0:ContentStream
            ns2:CostantiSdC.TipoFirmaFile
            ns3:DocAntivirusCheckSdC
            ns3:DocSdC
            ns3:DocTipologiaPdVSdC
            ns3:DocTipologiaSdC
            ns4:ExportSearchDocParam
            ns4:FilterPdAParam
            ns4:FilterPdDParam
            ns4:FilterPendingRequestParam
            ns3:LavoroSdC
            ns3:LogSdC
            ns3:OpzioniSdC
            ns2:PagingCriteria
            ns3:PdASdC
            ns3:PdDDownloadSdC
            ns3:PdDSdC
            ns3:PdVAntivirusSdC
            ns3:PdVPdDPreSdC
            ns3:PdVSdC
            ns0:PermissionDefinition
            ns0:PermissionMapping
            ns3:QueueOpSdC
            ns3:QueueOpTypeSdC
            ns3:RdAVSdC
            ns3:RdVSdC
            ns3:RemainingTimestampsSdC
            ns4:ReportPdARequestParam
            ns3:ReportPdASdC
            ns4:ReportPdVRequestParam
            ns3:ReportPdVSdC
            ns0:RepositoryCapabilities
            ns1:RepositoryEntry
            ns5:RepositoryService.ErrorData
            ns4:RequestMassivePdDParam
            ns4:RequestPdDParam
            ns3:SoggettoLavoroSdC
            ns3:SoggettoSdC
            ns2:SortingCriteria
            ns0:SupportedPermissions
            ns3:UtentePermessoSdC
            ns3:UtenteSdC
            ns0:VersioningState
            ns6:char
            ns6:duration
            ns6:guid
            ns0:repositoryInfo
--------------------------------------------------------------------------------
(KeyValueOfstringanyType){
   Key = None
   Value = None
 }
Traceback (most recent call last):
  File "C:/src/qa-lsd-webservices/qa-lsd-webservices/prova.py", line 64, in <module>
    contentStream=content_stream
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\client.py", line 559, in __call__
    return client.invoke(args, kwargs)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\client.py", line 612, in invoke
    soapenv = binding.get_message(self.method, args, kwargs)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\bindings\binding.py", line 120, in get_message
    content = self.bodycontent(method, args, kwargs)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\bindings\document.py", line 64, in bodycontent
    p = self.mkparam(method, pd, value)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\bindings\document.py", line 103, in mkparam
    tags.append(self.mkparam(method, pdef, item))
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\bindings\document.py", line 106, in mkparam
    return Binding.mkparam(self, method, pdef, object)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\bindings\binding.py", line 289, in mkparam
    return marshaller.process(content)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\mx\core.py", line 60, in process
    self.append(document, content)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\mx\core.py", line 73, in append
    self.appender.append(parent, content)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\mx\appender.py", line 102, in append
    appender.append(parent, content)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\mx\appender.py", line 243, in append
    Appender.append(self, child, cont)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\mx\appender.py", line 182, in append
    self.marshaller.append(parent, content)
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\mx\core.py", line 72, in append
    if self.start(content):
  File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\suds\mx\literal.py", line 87, in start
    raise TypeNotFound(content.tag)
suds.TypeNotFound: Type not found: 'Key'

Process finished with exit code 1

```

any suggestion please?

thanks.

**Comment by andreabisello** [comment]
the problem looks related to the webservices 

the backend needs something like

         <ns1:properties>
            <ns2:Key>PdV_VerificaFirmaFiles</ns2:Key>
            <ns2:Value>False</ns2:Value>
            <ns2:Key>Firma_OggettiProduttore</ns2:Key>
            <ns2:Value>False</ns2:Value>
         </ns1:properties>

even the wsdl creates something like 

         <tem:properties>
            
            <arr:KeyValueOfstringanyType>
               <arr:Key>?</arr:Key>
               <arr:Value>?</arr:Value>
            </arr:KeyValueOfstringanyType>
         </tem:properties>


even with soap ui.
