### ISSUE TITLE
WindowsHttpAuthenticated,  suds.transport.TransportError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by Dineshk77** [cackharot/suds-py3#55]
I am having the same issue. Below is my code and logs

code:
```
from suds.client import Client
from suds.transport.https import WindowsHttpAuthenticated
ntlm = WindowsHttpAuthenticated(username="domain\\"+username,password=password)
client = Client(url,transport=ntlm)
```

error logs:
```
HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "c:\Python3\lib\site-packages\suds\transport\http.py", line 63, in open
    return self.u2open(u2request)
  File "c:\Python3\lib\site-packages\suds\transport\http.py", line 119, in u2open
    return url.open(u2request, timeout=tm)
  File "c:\Python3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\Python3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\Python3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\Python3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\Python3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Development\github\fdoc-buildscripts\pythonLibs\Symbols.py", line 51, in uploadCer
    client = Client(self.cerServer["url"],transport=ntlm)
  File "c:\Python3\lib\site-packages\suds\client.py", line 110, in __init__
    self.wsdl = reader.open(url)
  File "c:\Python3\lib\site-packages\suds\reader.py", line 151, in open
    d = self.fn(url, self.options)
  File "c:\Python3\lib\site-packages\suds\wsdl.py", line 135, in __init__
    d = reader.open(url)
  File "c:\Python3\lib\site-packages\suds\reader.py", line 78, in open
    d = self.download(url)
  File "c:\Python3\lib\site-packages\suds\reader.py", line 94, in download
    fp = self.options.transport.open(Request(url))
  File "c:\Python3\lib\site-packages\suds\transport\https.py", line 61, in open
    return HttpTransport.open(self, request)
  File "c:\Python3\lib\site-packages\suds\transport\http.py", line 65, in open
    raise TransportError(str(e), e.code, e.fp)
suds.transport.TransportError: HTTP Error 401: Unauthorized
```
Note: 
- same code works for python2.7 (suds==0.4 and python-ntlm==1.1.0)
- Fails in python3.6 (suds-py3==1.3.3.0 and python-ntlm3==1.0.2)

_Originally posted by @Dineshk77 in https://github.com/cackharot/suds-py3/issues/36#issuecomment-588112187_

**Comment by cackharot** [comment]
@Dineshk77 Assume the issue is fixed in `python-ntlm3` lib and no fix/changes required on suds. If yes let me know I can close this. Thanks!

**Comment by Dineshk77** [comment]
@cackharot . nope python-ntlm3 is archived and I can't create issues there.

**Comment by joesafe** [comment]
@Dineshk77 Did you find an alternative on windows or work around this?

@cackharot Since python3-ntlm is not actively maintained anymore, any plans on moving away from this to an alternative?

**Comment by Dineshk77** [comment]
@joesafe I just forked the python-ntlm3 repo and replaced the HTTPNtlmAuthHandler.py using https://github.com/mullender/python-ntlm/blob/master/python30/ntlm/HTTPNtlmAuthHandler.py. and downloading my forked repo using pip for my scripts
```
git+git://github.com/Dineshk77/python-ntlm3@master#egg=python-ntlm3; python_version >= '3.0'
```

Kind of works but this adds the git dependency
